# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
     branches: main    
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        test: [one, two]
    runs-on: ubuntu-latest
    env:
      TEST: ${{matrix.test}}
    steps:
      - uses: actions/checkout@v3

      - name: Environment
        run: bash -c env | sort


